feat(sales): opportunity
Livl-Consulting/back pull request #2
Opened 2024-11-21 10:45 UTC by jvondermarck

2024-11-22 13:53 UTC, Bricklou requested changes
Globalement bon, il y a juste quelques petites parties à rectifier

2024-11-22 13:53 UTC, Bricklou commented on app/controllers/opportunities_controller.ts
> +    const { clientId } = request.qs()
Pourquoi pas via un params ? Sinon, tu peux aussi passer les querystring dans le validator si besoin (je ne sais plus comment par contre, il faudra éplucher la doc)

2024-11-22 13:53 UTC, Bricklou commented on app/controllers/opportunities_controller.ts
> +    if (clientId) {
Comme ça, cela sera mieux :slightly_smiling_face: 
```ts
const opportunities = await Opportunity.query()
    .preload('client')
    .if(clientId, (subQuery) => subQuery.where('clientId', clientId))
```

2024-11-22 13:53 UTC, Bricklou commented on app/validators/opportunity.ts
> +        status: vine.enum(['progress', 'validated', 'cancelled'])
Juste pour s'assurer qu'on ne fasse pas de faute débile
```ts
{
    status: vine.enum(['progress', 'validated', 'cancelled'] satisifies OpportunityStatusType[])
}
```

2024-11-22 13:54 UTC, Bricklou commented on app/controllers/opportunities_controller.ts
> +    const { clientId } = request.qs()
Update: il semblerait que tu ais juste à faire `vine.object({ clientId: vine.number() })` et cela devrait suffire (à vérifier)

2024-11-22 13:59 UTC, jvondermarck commented on app/controllers/opportunities_controller.ts
> +    if (clientId) {
Yes bien vu

2024-11-22 13:59 UTC, jvondermarck commented on app/validators/opportunity.ts
> +        status: vine.enum(['progress', 'validated', 'cancelled'])
Yes very good ça, j'avais zapp

2024-11-22 14:05 UTC, jvondermarck commented on app/controllers/opportunities_controller.ts
> +    const { clientId } = request.qs()
Yessss bien mieux !! Je fix ca

2024-11-22 14:34 UTC, Bricklou requested changes

2024-11-22 14:34 UTC, Bricklou commented on app/controllers/opportunities_controller.ts
> +    console.log("HEEH")
tu as oublié le console.log

2024-11-22 14:34 UTC, Bricklou commented on app/validators/opportunity.ts
> +        clientId: vine.number(),
inutile, nan ?

2024-11-22 14:37 UTC, jvondermarck commented on app/controllers/opportunities_controller.ts
> +    console.log("HEEH")
oupps

2024-11-22 14:37 UTC, jvondermarck commented on app/validators/opportunity.ts
> +        clientId: vine.number(),
pourquoi? c utilisé dans store et update

2024-11-22 14:44 UTC, Bricklou commented on app/validators/opportunity.ts
> +        clientId: vine.number(),
aah, pardon, j'ai confondu avec l'id d'opportunity

2024-11-22 14:45 UTC, Bricklou approved these changes

2024-11-22 14:45 UTC, jvondermarck commented on app/validators/opportunity.ts
> +        clientId: vine.number(),
pas de souciiis :)

2024-12-02 07:30 UTC, Bricklou approved these changes

2024-12-03 08:38 UTC, merged